### ISSUE TITLE
Fluxus API Checklist

### ISSUE THREAD

**Issue by shamansir** [shamansir/elm-fluxus#2]
## Scene

- [ ] `everyFrame` : `Renderer -> Graph`
- [ ] `display` : `Graph`

## Utils

- [ ] `when` : `Bool -> (a -> b) -> b` 
- [ ] `selfTest`
- [ ] `clear`

- [ ] `showFps`
- [ ] `desiredFps`

## State

- [x] `color` (instead of `colour` in Fluxus)
- [x] `translate` (different units in relation to Fluxus)
- [x] `rotate`
- [x] `scale`
- [x] `withState` : `(State -> State) -> State`

## Drawing

- [x] `drawCube` (size is different to Fluxus default)
- [ ] `drawSphere`
- [ ] `drawTorus`
- [ ] `drawPlane`
- [ ] `drawCylinder`
- [ ] `drawInstance` : `Primitive -> State` (currently `draw`)

- [ ] `pixelPrimitive`
- [ ] `pixelsUpload`

## Building

- [x] `buildCube` (returns an `Entity` itself, not an ID)
- [ ] `buildSphere`
- [ ] `buildPlane`
- [ ] `buildCylinder`
- [ ] `buildTorus`
- [ ] `buildPolygons`
- [ ] `buildLine`
- [ ] `buildSegPlane`
- [ ] `buildNurbsSphere`
- [ ] `buildNurbsPlane`
- [ ] `buildLocator`
- [ ] `buildBlobby`
- [ ] `destroy` : `Primitive`
- [ ] `withPrimitive` : `Primitive -> (Primitive -> State)`

## Object Tree

- [ ] `parent` : `Primitive`
- [ ] `detach` : `Primitive`

## Sound

- [ ] `startAudio` : `String -> Mbps -> HzRate`,  `jackPort mbps hz`
- [ ] `gh` : `Int -> Float`
- [ ] `gain` : `Float -> ?`

## Keyboard

- [ ] `keyPressed` : `String -> Bool`
- [ ] `keySpecialPressed` : `Int -> Bool`
- [ ] `keysDown` : `List String`

## Mouse

- [ ] `mouseX` : `Float`
- [ ] `mouseY` : `Float`
- [ ] `select` : `Float -> Float -> Float -> Int`, `select screenX screenY size = 0`

## OSC

- [ ] `oscSource` : `Int ->()`, `port`
- [ ] `oscMsg` : `String -> Bool`, `msg`

## Time

- [x] `time`
- [x] `delta`

## Primitives Materials

- [ ] `wireColour`
- [ ] `lineWidth`
- [ ] `pointWidth`
- [ ] `specular` : `Vec3`
- [ ] `ambient` : `Vec3`
- [ ] `emissive` : `Vec3`
- [ ] `shinyness` : `Vec3`
- [ ] `opacity` : `Float`
- [ ] `blendMode`

## Textures

- [ ] `texture` : `Image`
- [ ] `loadTexture` : `String -> Image`
- [ ] `clearTextureCache`
- [ ] `textureParams`
- [ ] `multiTexture`

## Light

- [ ] `makeLight`
- [ ] `lightPosition`
- [ ] `lightDirection`
- [ ] `lightDiffuse`
- [ ] `lightSpecular`
- [ ] `lightSpotAngle`
- [ ] `lightSpotExponent`

## Shadows

- [ ] `hintCastShadow`
- [ ] `shadowLight`

## Hints

- [ ] `hintNone`
- [ ] `hintNormal`
- [ ] `hintWire`
- [ ] `hintOrigin`
- [ ] `hintUnlit`

## Primitives

- [ ] `PData.Set`
- [ ] `PData.Ref`
- [ ] `PData.Size`
- [ ] `PData.Map`
- [ ] `PData.Fold`

...

## Text

- [ ] `buildType`
- [ ] `buildExtrudedType`
- [ ] `buildText`

## Camera

- [ ] `lockCamera`
- [ ] `cameraLag`
- [ ] `setCameraTransform`
- [ ] `resetCamera`

## Perspective

- [ ] `ortho`
- [ ] `setOrthoZoom`
- [ ] `persp`
- [ ] `clip`
- [ ] `fog`

## Random

- [ ] `rndf`
- [ ] `crndf`
- [ ] `grndf`
- [ ] `rndvec`
- [ ] `crndvec`
- [ ] `srndvec`
- [ ] `hsrndvec`
- [ ] `grndvec`

## Scene

- [ ] `getChildren`
- [ ] `getParent`

## Turtle

- [ ] `turtleReset`
- [ ] `turtlePrim`
- [ ] `buildLoop`
- [ ] `turtleBuild`
- [ ] `turlteTurn`
- [ ] `turtleMove`
- [ ] `turtleVert`
